### ISSUE TITLE
[feat] Rent Module UseCase 구현

### ISSUE THREAD

**Issue by kojaebo** [DeveloperAcademy-POSTECH/2024-MacC-A9-DOMADO#47]
## 기능 설명
Rent 패키지의 도메인 레이어에 UseCase를 구현하여 공유자전거 대여/반납 및 인수인계 비즈니스 로직을 구현합니다.

### 동기
- 공유자전거 대여/반납의 핵심 비즈니스 로직을 UseCase 계층에서 처리하여 도메인 규칙을 명확히 하고자 합니다.
- Clean Architecture의 원칙에 따라 비즈니스 로직을 UI와 데이터 계층으로부터 분리하여 유지보수성과 테스트 용이성을 향상시키고자 합니다.

### 완료 조건

스테이션 기반 대여/반납

- [ ]  QR 코드 스캔을 통한 자전거 식별
- [ ]  QR 코드 유효성 검증
- [ ] 스테이션과 자전거 정보 매칭 확인
- [ ]  대여 시작 처리
- [ ]  사용자의 대여 가능 상태 확인
- [ ]  자전거 잠금 해제
- [ ]  대여 정보 생성
- [ ]  대여 상태 관리
- [ ]  현재 대여 상태 조회
- [ ]  대여 시간 및 요금 계산
- [ ]  반납 처리
- [ ]  원래 대여 스테이션 확인
- [ ]  반납 완료 처리
- [ ]  최종 요금 계산

인수인계 기능

- [ ]  인수인계 요청
- [ ]  위치 기반 요청 생성
- [ ]  스테이션 근처 여부 확인
- [ ]  인수인계 매칭
- [ ] 요청자와 제공자 매칭
- [ ]  인수인계 상태 관리
- [ ]  인수인계 완료
- [ ]  기존 대여 종료
- [ ]  새로운 대여 시작
- [ ]  할인 요금 적용

### 추가 설명
- Core 패키지의 에러 핸들링 시스템 활용
- Location, Payment 패키지와의 상호작용 고려

**Comment by OneMoreThink** [comment]
여기서는 대여 / 반납을 위해 필요한 UseCase 목록만 정리하고 실제 각각의 Usecase에 대한 구현은 별도의 이슈를 발급한 이후 구체적인 구현 필요사항 및 계획등을 작성하여 해당 이슈에 대한 브랜치를 통해 작업을 진행하도록 합니다. 👀
