### ISSUE TITLE
[feat] Location Module ViewModel 구조 설계

### ISSUE THREAD

**Issue by leeymin130** [DeveloperAcademy-POSTECH/2024-MacC-A9-DOMADO#60]
# Location Module ViewModel 구현

## 기능 설명
지도 상에서 Hub와 HiBike의 위치를 표시하고, 각 항목 선택 시 상세 정보를 제공하는 ViewModel을 구현합니다. 
구현될 주요 기능은 다음과 같습니다.
- Hub와 HiBike의 위치 정보 표시
- Hub 선택 시 스테이션 별 자전거 현황 표시
- HiBike 선택 시 반납 예정 Hub 정보 표시
- 데이터 갱신 및 에러 처리

### 동기
Location Module의 Presentation 계층 구현을 위해 다음과 같은 필요성이 있습니다.
- Domain 계층(UseCase)과 UI 계층 사이의 데이터 흐름 관리
- 반응형 프로그래밍을 통한 실시간 UI 업데이트
- 복잡한 상태 관리의 캡슐화
- 테스트 가능한 구조 설계

### 완료 조건

1. **상태(State) 정의** 
   - [ ] 기본 상태 정의
     - 지도에 표시될 항목들 (`[MapDisplayable]`)
     - 선택된 항목 (Hub 또는 HiBike)
     - 선택된 Hub의 Station 목록
   - [ ] UI 상태 정의
     - 로딩 상태
     - 에러 상태
   - [ ] Computed Properties 정의
     - 선택된 Hub 접근자
     - 선택된 HiBike 접근자

2. **행위(Action) 정의**
   - [ ] 데이터 관리
     - 초기 데이터 로드
     - 데이터 새로고침
   - [ ] 선택 관리
     - 지도 아이템 선택
     - 선택 해제
   - [ ] 에러 처리
     - 에러 상태 초기화
     - 에러 메시지 처리

3. **UseCase 상호작용**
   - [ ] Hub 관련
     - Hub 위치 정보 fetch
     - 선택된 Hub의 Station 정보 fetch
   - [ ] HiBike 관련
     - HiBike 위치 정보 fetch

4. **Combine 스트림 처리**
   - [ ] Publisher 설정
     - 메인 스레드 UI 업데이트
     - 에러 핸들링
   - [ ] 메모리 관리
     - Cancellable 저장 및 해제
   - [ ] 상태 업데이트
     - Loading 상태 관리
     - Error 상태 관리

5. **ViewState Helper**
   - [ ] 상태 접근자 구현
     - Hub 상세정보 표시 상태
     - HiBike 상세정보 표시 상태
     - 로딩 상태
     - 에러 상태

### 참고 사항
- Entity와 UseCase는 이미 구현되어 있음
- MapDisplayable 프로토콜을 준수하는 객체들만 지도에 표시 가능
- SwiftUI의 Map 컴포넌트와 연동 필요

**Comment by OneMoreThink** [comment]
굳 진행시켜

**Comment by OneMoreThink** [comment]
다른 이슈로 이전
