### ISSUE TITLE
[feat] 주요 컴포넌트 추가 

### ISSUE THREAD

**Issue by kojaebo** [DeveloperAcademy-POSTECH/2024-MacC-A9-DOMADO#64]
## 기능 설명
Core 모듈에 재사용 가능한 공통 UI 컴포넌트 라이브러리를 구현합니다.

### 동기
- 앱 전반에서 일관된 디자인 시스템을 유지하기 위해 공통 컴포넌트가 필요합니다
- 각 모듈에서 중복 구현을 방지하고 코드 재사용성을 높일 수 있습니다
- UI 변경 시 한 곳에서 관리할 수 있어 유지보수가 용이해집니다

### 완료 조건 
- [x] Core/UI/Components 폴더 구조 생성
- [x] 스와이프 버튼 컴포넌트 구현
- [x] 바이크 주행 중 잠금해제/주차하기 버튼 컴포넌트 구현
- [x] 하이바이크로 전환하기 토글 구현

**Comment by OneMoreThink** [comment]
JB 디자인 시스템 정의된 컬러 모두 추가된거에요??🧐

**Comment by kojaebo** [comment]
> JB 디자인 시스템 정의된 컬러 모두 추가된거에요??🧐

컴포넌트에 필요했던 3가지만 일단 추가했어요..!
아,, 파인 하고 있는 줄 몰랐네요,,

**Comment by OneMoreThink** [comment]
고럼 색상 관련해서는 JB가 전부 추가해주세요

**Comment by morningfest** [comment]
ㅋㅋ 제이비 할 일 늘었대요

**Comment by kojaebo** [comment]
> ㅋㅋ 제이비 할 일 늘었대요

,,ㅎㅎ 
행복해요,,

선생님, 디자인 시스템 어디서 볼 수 있죠..?

**Comment by morningfest** [comment]
> > ㅋㅋ 제이비 할 일 늘었대요
> 
> ,,ㅎㅎ 행복해요,,
> 
> 선생님, 디자인 시스템 어디서 볼 수 있죠..?
<img width="1159" alt="스크린샷 2024-11-20 오후 11 57 30" src="https://github.com/user-attachments/assets/00df4acc-a52a-4616-8615-3c566b1ca09b">
여기요

**Comment by morningfest** [comment]
근데 이름 임의로 제가 정해놨는데, 더 구분하기 쉬운 이름 있다면 바꾸셔도 무관..
