### ISSUE TITLE
[feat] 자전거 대여 화면 구현

### ISSUE THREAD

**Issue by kojaebo** [DeveloperAcademy-POSTECH/2024-MacC-A9-DOMADO#79]
## 기능 설명
- 화면에 필요한 UI를 Hi-Fi에 맞게 구성합니다.

### 동기
- 앱 시연을 위한 화면을 우선적으로 구현합니다.

### 완료 조건
- [ ] 주행 중 화면
- [ ] 바이크 주차하기 화면
- [ ] 하이바이크로 전환하기 화면
- [ ] 바이크 반납 완료 화면
- [ ] 바이크 반납하기 화면

**Comment by OneMoreThink** [comment]
해당 이슈에서 명시하고 있는 모든 화면  #82 #86 에서 추가 완료했습니다 ~!
