### ISSUE TITLE
[bug] 지도상 마커 터치가 정상적으로 동작하지 않습니다. 

### ISSUE THREAD

**Issue by OneMoreThink** [DeveloperAcademy-POSTECH/2024-MacC-A9-DOMADO#93]
## 버그 설명
지도상에 마커를 클릭하면 제대로 동작하지 않습니다. 

### 재현 방법
1. 대여가능한 자전거를 확인하기 위해 지도상의 마커를 선택합니다. 

### 기대한 동작
- 선택한 마커에 맞는 카드뷰가 화면상에 등장합니다. 

### 실제 동작
- 선택했을때 버튼이 동작하지 않습니다. 

### 추가 설명
마커 간의 중첩으로 인한 터치 영역에 문제가 의심됩니다.

**Comment by leeymin130** [comment]
마커 동작...안해...?ㅜㅜ

**Comment by OneMoreThink** [comment]
> 마커 동작...안해...?ㅜㅜ

안눌려 ㅠㅠ

**Comment by leeymin130** [comment]
> > 마커 동작...안해...?ㅜㅜ
> 
> 안눌려 ㅠㅠ

🥹...
앗 혹시 선택 취소를 탭제스쳐로 해서 그런가
마커 선택이랑 중복돼서..?(궁예)
